.PHONY: up down

all: up # default target

# -------------------------------------------------
# start and stop docker compose
# -------------------------------------------------

up:
	docker-compose up --build -d

down:
	docker-compose down
